# Generated by Django 4.2.7 on 2025-04-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='群组代码')),
                ('name', models.CharField(max_length=255, verbose_name='群组名称')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='群组编号')),
                ('qr_code', models.CharField(default='/placeholder.svg?height=300&width=300', max_length=255, verbose_name='二维码路径')),
                ('type', models.CharField(choices=[('course', '课群'), ('major', '专业群'), ('life', '生活群')], max_length=20, verbose_name='群组类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '群组',
                'verbose_name_plural': '群组',
                'ordering': ['type', 'code'],
            },
        ),
    ]
