# Generated by Django 4.2.7 on 2025-04-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_qr_code_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='qr_code_data',
        ),
    ]
