# Generated by Django 4.2.7 on 2025-04-11 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_grouprequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Community',
        ),
        migrations.RenameModel(
            old_name='GroupRequest',
            new_name='JoinRequest',
        ),
        migrations.AlterModelOptions(
            name='joinrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '加群申请', 'verbose_name_plural': '加群申请'},
        ),
    ]
