# Generated by Django 4.2.7 on 2025-04-11 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_rename_group_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请用户'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='用户邮箱'),
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户姓名'),
        ),
    ]
