# Generated by Django 4.2.7 on 2025-04-11 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_joinrequest_user_joinrequest_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='user_name',
        ),
    ]
